### ISSUE TITLE
how work with mutate

### ISSUE THREAD

**Issue by Suro4ek** [nanostores/query#14]
as I understand it, I should just return fetch inside createMutatorStore, but is it possible to make a request to the mutate as in swr there in mutate useSWR('/api/user', fetcher)?

**Comment by dkzlv** [comment]
@Suro4ek Hey there! 👋

First, [here's a repro](https://stackblitz.com/edit/react-ts-qkamg4?file=App.tsx) of the mutation that catches errors. Try clicking on +5 or -5 buttons, you'll see that in 20% of cases it reverts the changes to the cache and shows an error. So if something doesn't return errors to you, can you please provide a repro on stackblitz?

Second is this:

> but is it possible to make a request to the mutate as in swr there in mutate useSWR('/api/user', fetcher)?

I'm not sure what you're talking about here 🤔 If you're talking about [bound mutator](https://swr.vercel.app/docs/mutation.en-US#bound-mutate), then yes, [we have it](https://github.com/nanostores/query#refetching-and-manual-mutation). But we typically advice to use mutation stores ([`useSWRMutation` in SWR terms](https://swr.vercel.app/docs/mutation.en-US#useswrmutation)). Again, feel free to expand on your thoughts in code/stackblitz/whatever.

**Comment by dkzlv** [comment]
I'll close it for now, feel free to reopen if something's missing/unclear.
