### ISSUE TITLE
Feature Request: `invalidate()` in mutatorStore doesn't accept a key matcher function

### ISSUE THREAD

**Issue by Bwvolleyball** [nanostores/query#20]
The `invalidate()` function from the `createMutatorStore` concept doesn't seem to accept anything but a string - can it accept a key matcher function as well similar to the `invalidateKeys()` function?

**Comment by dkzlv** [comment]
@Bwvolleyball Yeah, sure. Added in 0.2.3, [here's a demo](https://stackblitz.com/edit/react-ts-qlpps9?file=App.tsx). Thanks for your issue!

**Comment by Bwvolleyball** [comment]
Thanks for the quick turnaround @dkzlv ! We're loving this project as we get the hang of it!
