### ISSUE TITLE
Fetcher store always returns `loading: true` when used with svelte

### ISSUE THREAD

**Issue by moaali** [nanostores/query#22]
When using with Svelte I noticed that the query gets stuck at loading state even after the promise fulfils.

![Screenshot 2023-10-29 at 9 55 20 PM](https://github.com/nanostores/query/assets/22148098/0059185b-d9b4-4a0d-abda-3c65df351a2c)

Reproduction: https://stackblitz.com/edit/svelte-spaceymen-3i3kjn

**Comment by dkzlv** [comment]
@moaali Hey!

No bug here: you destructure the values once and instantly unsubscribe. If you want reactivity, you should pick a different syntax. The following will work:

```html
<script>
  import {posts} from './stores/posts'

  $: ({loading, data} = $posts);
</script>

<div>
  {#if loading}
    loading...
  {:else if data}
    {data.title}
  {:else}
    error
  {/if}
</div>
```

In any case, I recommend getting a fresh look [at Svelte's `$:` statement](https://svelte.dev/docs/svelte-components#script-3-$-marks-a-statement-as-reactive).
