### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by artem-shkurenko** [nanostores/query#3]
The problem is reproduced on Vite.

Create base fetcher and store. 

I see it in the console:
```
10297 deduped [my key]
5883 already runs [my key]
```

[Example on StackBlitz](https://stackblitz.com/edit/vitejs-vite-8edzcr)

**Comment by j** [comment]
@artem-shkurenko I just ran this with `0.0.4` and it ran.

**Comment by dkzlv** [comment]
There seems to be a problem connected to _Vite_ in _Stackblitz_ itself, not nanoquery. Here, same example, but on [codesandbox](https://codesandbox.io/s/keen-cookies-yqdm8v?file=/src/App.js).

The link works (and worked) good on my machine (MBP on Apple Silicon), but it doesn't (and didn't) work on my colleagues' machines running on Linux/Windows. It does work locally everywhere though, whatever processor arch/OS you have.
![image](https://user-images.githubusercontent.com/2846746/224745529-3dcdb245-2b89-449e-8e94-294bffdfb17d.png)


I filed [an issue](https://github.com/stackblitz/webcontainer-core/issues/987) in SB's repo, so far no answer.

I'll close this as it isn't really nanoquery-specific and I can't do anything with it at all.

**Comment by artem-shkurenko** [comment]
I also have a problem with local development.

Mac: Intel Core i7
Mac OS: 13.0.1 (22A400)
Vite: 4.1.1
