### ISSUE TITLE
Suggestion: Add `isPending` State

### ISSUE THREAD

**Issue by martinmckenna** [nanostores/query#37]
both fetcher and mutator stores return a loading, data and error state, but the issue here is that if your app needs to show some kind of empty state, you will get a flash of empty state before the `loading` gets set to `true`

That means in a React component like this for example:

```tsx
const { data, loading, error } = useStore($someQuery)

if(loading) {
   return <span>loading</span>
}

if(error) {
  return <span>{error}</span>
}

if(!data) {
   return <span>no data here!<span />
}

return data.map(eachThing => ....)
```

the "no data here" condition flashes quickly before the loading state appears

React query solves this by exposing an additional property called `isPending`:

> For most queries, it's usually sufficient to check for the isPending state, then the isError state, then finally, assume that the data is available and render the successful state:

https://tanstack.com/query/latest/docs/framework/react/guides/queries#query-basics

If this library returned this additional property before the request has been fired off, the consuming UI could use it to show a loading state without getting a flash before the loading state is set to `true`

**Comment by dkzlv** [comment]
I'll close it for now, lmk if there's something unclear or still worth opening.

**Comment by martinmckenna** [comment]
yeah I mean we definitely implemented some computed values from the base loading and data states. For example, a lot of our components look like this:

```tsx
const {loading, error, data} = useStore()

const noData = typeof data === "undefined"
const isFirstLoad = loading && noData

if(isFirstLoad || noData) {
   return <span>loading....</span>
}

if(error) {
   return <span>error</span>
}

return <Blah />
```

This is to solve 2 issues.

1. We don't want to re-show the loading state if the user is taking an action that's going to invalidate the data because we choose to show the old data until the new data becomes available
2. We don't want to flash a no data state before the loading state kicks in. We want the page to initialize with the loading UI

So for these reasons, having a state that implies the request hasn't fired off yet would be a nice-to-have and prevent us from writing a bunch of extra code in the consuming code.

**Comment by martinmckenna** [comment]
```
const Post = () => {
  const { data, loading } = useStore($currentPost);

  if (data) return <div>{data.content}</div>;
  if (loading) return <>Loading...</>;
  
  return <>Error!</>;
};
```

this will show `<>Error</>` for a split second before the `loading` gets set to `true`

**Comment by dkzlv** [comment]
> this will show <>Error</> for a split second before the loading gets set to true

😨
tis not gud

**Comment by martinmckenna** [comment]
yep. I think that's why react query has separate `isLoading` and `isPending` states, and recommends you only really need to do checking on `isPending`
