### ISSUE TITLE
$store.set() not triggering the fetcher store

### ISSUE THREAD

**Issue by hemandev** [nanostores/query#39]
I have a fetcher that has a dependent value on another store.
```ts
const [createFetcherStore, createMutatorStore] = nanoquery({
    fetcher: async (...keys: (string | number)[]) => {
      const methodName = keys[0] as keyof Instance['notification'];
      if (methodName === 'get') {
        console.log('page no is...', keys[1]);
        return instance.notification.get({
          pageNo: keys[1] as number,
          limit: 3,
        });
      }
    },
  });
  
  const $currentPage = atom(1);
  const $notificationStore = createFetcherStore<Notification>([
    'get',
    $currentPage,
  ]);
  ```
  I have a function in vanilla js `loadMore()`
  
```ts
    const loadMore = async () => {
     $currentPage.set($currentPage.get() + 1);
    };
  ```
I am trying to use these in vanilla js using the `listen()`.
  
But calling `loadMore()` is not triggering the `$notificationStore`. Why?
Shouldn't the `$currentPage` store change trigger the `$notificationStore` ?

**Comment by dkzlv** [comment]
Hey there, @hemandev!

[The reactivity on the library side works](https://stackblitz.com/edit/react-ts-d4xq2z?file=App.tsx) (and it's pretty thoroughly tested as well!). Vanilla or not, all framework libraries essentially wrap `.listen` with framework-specific memoization, [like in `@nanostores/react`](https://github.com/nanostores/react/blob/main/index.js#L8-L9).
And, most probably, it's not a reactivity issue in nanostores as well, as the code that sets the Promise result value is [extremely straightforward](https://github.com/nanostores/query/blob/main/lib/main.ts#L216-L222).

The issue with your code, as I think, lies in what `instance.notification.get` function returns, but without the actual implementation details I can't point to an exact issue.
Can you try to come up with an isolated reproduction case on Stackblitz?

**Comment by hemandev** [comment]
Thanks for the quick response @dkzlv.
I was able to spin up a basic repro sandbox here. Would you mind taking a look?
https://codesandbox.io/p/sandbox/silly-chandrasekhar-ng2tkg

My expectation is that the `subscribe()` will get called with the new todo values on calling `loadMore()`

**Comment by dkzlv** [comment]
@hemandev Hm, yeah, the issue is in `onNotify` hook (if you comment it out and change `$todo?.data` for `$todo.value?.data`, all works as expected), but I don't know exactly why. I'll keep the issue open and see what my cause it either in `query` or in core.

**Comment by hemandev** [comment]
Yeah, that did fix it. 
Unfortunately, I was using `onNotify` to keep appending all the fetched `todos` to another store. 
Let me see if I can figure another way to do it. Thanks again.

**Comment by dkzlv** [comment]
@hemandev `onSet` definitely works.

**Comment by hemandev** [comment]
I tried with `onSet` first. But it was not getting triggered always. You can try in this same sandbox.
It calls twice, `{loading: false}, `{loading: true, data: <Promise>}` and stops.
It never called the 3rd time with the resolved value.

**Comment by dkzlv** [comment]
@hemandev Ok, I managed to pinpoint the issue, but I don't know why that happens.

Both `onNotify` and `onSet` work, but you need to either use `$todo.value` in `onNotify` or destructure `newValue` from payload in `onSet` like [in this example](https://github.com/nanostores/nanostores?tab=readme-ov-file#store-events). For some reason using `.get()` breaks all of this thing, even though [it's basically calling `.value`](https://github.com/nanostores/nanostores/blob/main/atom/index.js#L8-L13).

**Comment by hemandev** [comment]
Yep, that is working 🎉
