### ISSUE TITLE
Warning when using a React component in an Astro project

### ISSUE THREAD

**Issue by JacobZwang** [nanostores/query#49]
When using nanoquery in a react component in an astro project I get this warning in the console. I'm not familiar enough with react to completely understand this warning so I'm not sure if this is a problem or not.
> Warning: The result of getServerSnapshot should be cached to avoid an infinite loop
    at NanoQueryExample (http://localhost:4322/src/components/nanoquery.tsx:31:29)

https://stackblitz.com/github/JacobZwang/nanoquery-astro-broken-example
https://github.com/JacobZwang/nanoquery-astro-broken-example

**Comment by sitarass** [comment]
m2 in nextjs project

**Comment by sitarass** [comment]
@dkzlv check [here](https://stackblitz.com/edit/react-ts-zjwuwa?file=App.tsx) the error
<img width="547" alt="image" src="https://github.com/user-attachments/assets/26c8715c-0032-41f2-9eb8-a95f1e103148">

**Comment by dkzlv** [comment]
This is not a bug, just excessive logging by React.

Refer [to this comment](https://github.com/nanostores/query/issues/33#issuecomment-1966239835), header `getSnapshot should be cached `.
