### ISSUE TITLE
[bug] create FetcherStore inside FC and it never get updates on react 18

### ISSUE THREAD

**Issue by sintell** [nanostores/query#5]
Example from [Local state and Pagination](https://github.com/nanostores/query/tree/main#local-state-and-pagination) does not work  with react 18
I've made a quick [example on codesandbox](https://codesandbox.io/s/clever-bassi-m7irsx?file=/src/App.tsx) to reproduce this issue

### Problem description:
`useStore($fetcherStore)` never returns an updated data, thou network call is completed successfully and Promise resolves without an error
So my component never re-renders with an actual data

### What happens
I debugged it down to the [store.notify()](https://github.com/nanostores/nanostores/blob/c32105e893cf6e099e4f2867b7aa4396822033e1/atom/index.js#L16) call, after calling `set` in [here](https://github.com/nanostores/query/blob/95e17c98074eb57f8ee5f2a5bd58d3d73923f862/lib/main.ts#L97)
When `notify` got called it has no `currentListeners` or `nextListeners` [here](https://github.com/nanostores/nanostores/blob/c32105e893cf6e099e4f2867b7aa4396822033e1/atom/index.js#L25) so no one gets notified about the state change

I've checked that this is the case only for react 18 with new batching mode ON, so my guess it's somehow connected to the [Automatic Batching](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#automatic-batching) feature

It is possible that actual problem lies somewhere in the upstream @nanostores but I could not figure out where to look next

Hope you could help and clarify this issue, thanks for the great lib by the way!

**Comment by dkzlv** [comment]
@sintell Thanks for your report, that's very helpful!

Fixed the issue in 0.0.5, [here's a repro example on Stackblitz](https://stackblitz.com/edit/react-ts-vpuysl?file=App.tsx).
