### ISSUE TITLE
Inconsistent Data Loading with Nano Stores Query and Vue.js

### ISSUE THREAD

**Issue by misl-smlz** [nanostores/query#52]
### Description:

We are experiencing an issue with Nano Stores Query in combination with Vue.js. The data loading is inconsistent, sometimes the data does not load correctly. We use session storage as cache for Nano Stores Query.

### Reproduction Steps:

1. Go to the following example: [StackBlitz Example](https://stackblitz.com/edit/github-ysvv8s-q5a1kr?file=src%2Fpages%2Findex.astro)
2. Log in to see the username displayed.
3. Reload the page or navigate to the second page (which looks the same).

Expected Behavior:

After reloading the page or navigating to the second page, the user should remain logged in, and the username should be displayed.

### Actual Behavior:

Sometimes the user remains logged in and the username is displayed, but other times it does not. Please reload or navigate a few times, it does not always happen - it seems to be a race condition. The console log messages vary based on success or failure.

### Console Log Messages:

Success:

![image](https://github.com/user-attachments/assets/4c191ec7-abf6-4e59-b411-405587040f00)

Failure:

![image](https://github.com/user-attachments/assets/647f5475-8f0a-4ab6-91a7-1b4dcc17452f)

### Additional Information:

Vue.js version: 3.4
Nano Stores version: 0.10
Browser: Chrome 126

Thank you for looking into this issue. Please let me know if you need any further information or I can help in any way.

**Comment by dkzlv** [comment]
@misl-smlz Hey! Sorry for late response. Can you update the demo? It seems the API calls to dummyjson are incorrect: when I press sign in it doesn't do anything besides reloading the page with no visible effect. Couldn't figure out the reason quickly.

**Comment by misl-smlz** [comment]
@dkzlv Here is an updated version: https://stackblitz.com/edit/github-ysvv8s-q5a1kr?file=src%2Fapi.ts

(Seems like an Google/Edge Update broke the example, in Firefox the original version is still working)

**Comment by misl-smlz** [comment]
@dkzlv Any update on this?

**Comment by mseele** [comment]
I have now been able to reproduce the problem without Vue.js. It is now a vanilla astro project with javascript:

https://stackblitz.com/edit/github-pzhgbv?file=src%2Fcomponents%2FCurrentUser.astro

Still the same problem: When logging in and changing the page, sometimes the user is not loaded by nanostores although it is present in the sessionStorage.

@dkzlv I would really appreciate it if you would take a look at the example. Maybe we are just doing something wrong. Thanks.

**Comment by misl-smlz** [comment]
It's not a nanostore problem, it's a JSON problem: `JSON.stringify` cannot handle `Number.POSITIVE_INFINITY`. And `NanoqueryValue` uses `Number.POSITIVE_INFINITY` in its `expires` attribute.

Fixing that resoles the bug:

```typescript
/**
 * Nanoquery value type.
 */
type NanoqueryValue = {
    data?: unknown;
    error?: unknown;
    retryCount?: number;
    created?: number;
    expires?: number;
};

function serialize(_key: string, value: unknown) {
    if (value === Number.POSITIVE_INFINITY) {
        return 'POSITIVE_INFINITY';
    }
    return value;
}

function deserialize(_key: string, value: unknown) {
    if (value === 'POSITIVE_INFINITY') {
        return Number.POSITIVE_INFINITY;
    }
    return value;
}

/**
 * Nanoquery cache implementation using session storage.
 */
export class SessionStorageCache extends Map<string, NanoqueryValue> {
    private cacheKey: string;

    constructor(cacheKey = 'nanoquery') {
        super();
        this.cacheKey = cacheKey;
    }

    private sessionStorageKey(value: string) {
        return `${this.cacheKey}-${value}`;
    }

    set(key: string, value: NanoqueryValue) {
        super.set(key, value);
        sessionStorage.setItem(this.sessionStorageKey(key), JSON.stringify(value, serialize));
        return this;
    }

    get(key: string) {
        const value = super.get(key);
        if (value !== undefined) {
            return value;
        }

        const sessionStorageValue = sessionStorage.getItem(this.sessionStorageKey(key));
        if (sessionStorageValue !== null) {
            const value = <NanoqueryValue>JSON.parse(sessionStorageValue, deserialize);
            return value;
        }

        return undefined;
    }

    delete(key: string) {
        const result = super.delete(key);
        sessionStorage.removeItem(this.sessionStorageKey(key));
        return result;
    }
}

```
