### ISSUE TITLE
revalidateOnFocus

### ISSUE THREAD

**Issue by sitarass** [nanostores/query#54]
@dkzlv revalidateOnFocus option doesn't work :(

**Comment by dkzlv** [comment]
@sitarass Can you provide more information? [This demo](https://stackblitz.com/edit/react-ts-ncflns?file=App.tsx) works perfectly for me.

https://github.com/user-attachments/assets/bfce6cca-2713-4121-b669-2f23d9b5f257

I'll close for now as I'm almost sure this is some misunderstanding and not a real bug. Feel free to add more information here!

**Comment by sitarass** [comment]
@dkzlv I made an isolated reproduction, check it [here](https://stackblitz.com/edit/react-ts-zjwuwa?file=App.tsx).

**Comment by dkzlv** [comment]
@sitarass It works as well. Precisely as it should.

Please, stick to steps/expected/actual form.

**Comment by sitarass** [comment]
@dkzlv when you switch between e.g. tabs and made a refocus on the above one, api call not called again, I didn't see a refetch on network

**Comment by sitarass** [comment]
@dkzlv Did I get something wrong?

**Comment by dkzlv** [comment]
@sitarass Yep.

https://github.com/user-attachments/assets/634bd6aa-38e2-475b-9595-f79d1356cb5b

**Comment by sitarass** [comment]
@dkzlv Ok thanks, you're right, it works exactly as it should.
But I am noticing that when I have the dev tools tab open it does not work :( .
I tested with ui with the dev tools tab closed.
