### ISSUE TITLE
Feat: tRPC Wrapper 

### ISSUE THREAD

**Issue by Brian-McBride** [nanostores/query#6]
Thanks for the library. I like what you are doing here. 
Tanstack Query is a great lib, but I am so happy to see more and more people breaking out of the "React Only" mindset. 

tRPC has gotten pretty popular, and I think a client wrapper that offers all the typing in tooling like Astro. build would be pretty awesome. https://trpc.io/docs/client/introduction

**Comment by dkzlv** [comment]
Hey, Brian!

Thanks for the suggestion!

Truth be told, I don't think that's currently possible. `trpc/client` has a rather convoluted API, and it only makes sense for their authors. I know there's [a community-driven client for swr](https://github.com/sannajammeh/trpc-swr) that will probably work at some point. If you're interested in creating such a wrapper for nanoquery, that'll be magnificent, but as for us I think that's outside of our scope. We're focusing primarily on the basics of the nanostores ecosystem, such as state management, network, routing, forms, SSR and so on.
